# PostgreSQL Database Service
services:
  crm-pg:
    image: postgres:15.2-alpine
    container_name: crm-pg
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crm_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    volumes:
      - crm-pg:/var/lib/postgresql/data
    networks:
      - crm-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-crm_dev}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  crm-pg:
    driver: local

networks:
  crm-network:
    driver: bridge
