version: '3.8'

services:
  crm-pg:
    image: postgres:15.2-alpine
    container_name: crm-pg
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - crm-pg:/var/lib/postgresql/data
    networks:
      - crm-network

volumes:
  crm-pg:
    driver: local

networks:
  crm-network:
    driver: bridge
