[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = false

[tool.pylsp-mypy.plugin]
ignore_missing_imports = true
ignore_errors = [
    "django",
    "rest_framework",
    "migrations"
]

[tool.ruff]
target-version = "py39"
line-length = 88
select = ["E", "F", "I", "N", "W", "B", "C4", "UP"]
ignore = [
    "E501",  # line too long
    "E722",  # do not use bare except
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"migrations/*" = ["E501", "F401"]
