"""
This type stub file was generated by pyright.
"""

import functools

class IntConverter:
    regex = ...
    def to_python(self, value): # -> int:
        ...
    
    def to_url(self, value): # -> str:
        ...
    


class StringConverter:
    regex = ...
    def to_python(self, value):
        ...
    
    def to_url(self, value):
        ...
    


class UUIDConverter:
    regex = ...
    def to_python(self, value): # -> UUID:
        ...
    
    def to_url(self, value): # -> str:
        ...
    


class SlugConverter(StringConverter):
    regex = ...


class PathConverter(StringConverter):
    regex = ...


DEFAULT_CONVERTERS = ...
REGISTERED_CONVERTERS = ...
def register_converter(converter, type_name): # -> None:
    ...

@functools.cache
def get_converters(): # -> dict[str | Any, IntConverter | PathConverter | SlugConverter | StringConverter | UUIDConverter | Any]:
    ...

def get_converter(raw_converter): # -> IntConverter | PathConverter | SlugConverter | StringConverter | UUIDConverter:
    ...

