# Generated by Django 5.2.5 on 2025-08-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_current'], name='entity_is_current_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_current', 'display_name'], name='entity_current_name_idx'),
        ),
        migrations.AlterModelTable(
            name='entity',
            table='entity',
        ),
    ]
