# Generated by Django 5.2.5 on 2025-08-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_entity_entity_is_current_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='hashdiff',
            field=models.CharField(default='placeholder_hash_to_be_computed', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_uid', 'is_current'], include=('display_name', 'entity_type', 'valid_from'), name='ent_uid_curr_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_current', 'entity_type'], include=('entity_uid', 'display_name', 'valid_from'), name='ent_curr_type_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['valid_from'], include=('entity_uid', 'display_name', 'entity_type', 'is_current'), name='ent_valid_from_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['display_name'], include=('entity_uid', 'entity_type', 'is_current', 'valid_from'), name='ent_name_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entitydetail',
            index=models.Index(fields=['entity', 'is_current'], include=('detail_type', 'detail_value', 'valid_from'), name='det_ent_curr_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entitydetail',
            index=models.Index(fields=['entity', 'detail_type', 'is_current'], include=('detail_value', 'valid_from'), name='det_ent_type_curr_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entitydetail',
            index=models.Index(fields=['entity', 'valid_from'], include=('detail_type', 'detail_value', 'is_current'), name='det_ent_valid_from_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entitydetail',
            index=models.Index(fields=['detail_type', 'is_current'], include=('entity', 'detail_value', 'valid_from'), name='det_type_curr_cov_idx'),
        ),
        migrations.AddIndex(
            model_name='entitydetail',
            index=models.Index(fields=['hashdiff'], include=('entity', 'detail_type', 'detail_value'), name='det_hashdiff_cov_idx'),
        ),
    ]
