# Generated by Django 5.2.5 on 2025-09-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entitytype'),
        ),
        migrations.AlterField(
            model_name='entitydetail',
            name='detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.detailtype'),
        ),
    ]
