"""
This type stub file was generated by pyright.
"""

def async_unsafe(message): # -> _Wrapped[..., object, ..., object] | Callable[..., _Wrapped[..., Any, ..., Any]]:
    """
    Decorator to mark functions as async-unsafe. Someone trying to access
    the function while in an async context will get an error message.
    """
    ...

