"""
This type stub file was generated by pyright.
"""

"""
Utility functions for generating "lorem ipsum" Latin text.
"""
COMMON_P = ...
WORDS = ...
COMMON_WORDS = ...
def sentence(): # -> str:
    """
    Return a randomly generated sentence of lorem ipsum text.

    The first word is capitalized, and the sentence ends in either a period or
    question mark. Commas are added at random.
    """
    ...

def paragraph(): # -> str:
    """
    Return a randomly generated paragraph of lorem ipsum text.

    The paragraph consists of between 1 and 4 sentences, inclusive.
    """
    ...

def paragraphs(count, common=...): # -> list[Any]:
    """
    Return a list of paragraphs as returned by paragraph().

    If `common` is True, then the first paragraph will be the standard
    'lorem ipsum' paragraph. Otherwise, the first paragraph will be random
    Latin text. Either way, subsequent paragraphs will be random Latin text.
    """
    ...

def words(count, common=...): # -> LiteralString:
    """
    Return a string of `count` lorem ipsum words separated by a single space.

    If `common` is True, then the first 19 words will be the standard
    'lorem ipsum' words. Otherwise, all words will be selected randomly.
    """
    ...

