"""
This type stub file was generated by pyright.
"""

from xml.sax.saxutils import XMLGenerator

"""
Utilities for XML generation/parsing.
"""
class UnserializableContentError(ValueError):
    ...


class SimplerXMLGenerator(XMLGenerator):
    def addQuickElement(self, name, contents=..., attrs=...): # -> None:
        "Convenience method for adding an element with no children"
        ...
    
    def characters(self, content): # -> None:
        ...
    
    def startElement(self, name, attrs): # -> None:
        ...
    


